apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-workload
  name: example-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-workload
  template:
    metadata:
      labels:
        app: example-workload
    spec:
      containers:
        - image: alpine:3.13.5
          name: alpine
          command: ['sh', '-c', 'sleep 365d']
